insert into user(id, username, password, name) values (1, "long", "21232f297a57a5a743894a0e4a801fc3", "Long Nguyen")
insert into item(id, code, name) values (1, "homework", "Homework")
insert into task(id, title, isDone, date, item_id) values (1, "Clean house", TRUE, "2022-04-10", 1)
insert into item(id, code, name) values (2, "company", "Company")
insert into task(id, title, isDone, date, item_id) values (2, "TODO Project", FALSE, "2022-04-10", 2)
insert into item(id, code, name) values (3, "university", "University")
insert into task(id, title, isDone, date, item_id) values (3, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (4, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (5, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (6, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (7, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (8, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (9, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (10, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (11, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (12, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (13, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (14, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (15, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (16, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (17, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (18, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (19, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (20, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (21, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (22, "Course project", FALSE, "2022-04-10", 3)
insert into task(id, title, isDone, date, item_id) values (23, "Course project", FALSE, "2022-04-10", 3)



